// <auto-generated />
using System;
using EnrollmentSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EnrollmentSystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241012202240_dept")]
    partial class dept
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.33")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EnrollmentSystem.Models.Entities.Course", b =>
                {
                    b.Property<int>("course_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("course_id"), 1L, 1);

                    b.Property<string>("course_code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("course_desc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("course_title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dept_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("course_id");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("EnrollmentSystem.Models.Entities.Department", b =>
                {
                    b.Property<int>("dept_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("dept_id"), 1L, 1);

                    b.Property<string>("dept_code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dept_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("dept_id");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("EnrollmentSystem.Models.Entities.Enroll", b =>
                {
                    b.Property<int>("enroll_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("enroll_id"), 1L, 1);

                    b.Property<int?>("Semestersem_id")
                        .HasColumnType("int");

                    b.Property<int?>("Studentstud_id")
                        .HasColumnType("int");

                    b.Property<int>("Subjectsubj_id")
                        .HasColumnType("int");

                    b.Property<int>("course_id")
                        .HasColumnType("int");

                    b.Property<string>("encodedby")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("enroll_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("room_id")
                        .HasColumnType("int");

                    b.HasKey("enroll_id");

                    b.HasIndex("Semestersem_id");

                    b.HasIndex("Studentstud_id");

                    b.HasIndex("Subjectsubj_id");

                    b.HasIndex("course_id");

                    b.HasIndex("room_id");

                    b.ToTable("Enrolls");
                });

            modelBuilder.Entity("EnrollmentSystem.Models.Entities.Room", b =>
                {
                    b.Property<int>("room_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("room_id"), 1L, 1);

                    b.Property<string>("room_code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("room_type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("room_id");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("EnrollmentSystem.Models.Entities.Semester", b =>
                {
                    b.Property<int>("sem_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("sem_id"), 1L, 1);

                    b.Property<DateTime>("sem_end")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("sem_start")
                        .HasColumnType("datetime2");

                    b.Property<string>("sem_year")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("sem_id");

                    b.ToTable("Semesters");
                });

            modelBuilder.Entity("EnrollmentSystem.Models.Entities.Student", b =>
                {
                    b.Property<int>("stud_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("stud_id"), 1L, 1);

                    b.Property<string>("stud_address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("stud_email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("stud_fname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("stud_lname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("stud_mname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("stud_phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("stud_section")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("stud_id");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("EnrollmentSystem.Models.Entities.Subject", b =>
                {
                    b.Property<int>("subj_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("subj_id"), 1L, 1);

                    b.Property<string>("subj_code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("subj_days")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("subj_endtime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("subj_starttime")
                        .HasColumnType("datetime2");

                    b.HasKey("subj_id");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("EnrollmentSystem.Models.Entities.User", b =>
                {
                    b.Property<int>("user_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("user_id"), 1L, 1);

                    b.Property<int>("can_add")
                        .HasColumnType("int");

                    b.Property<int>("can_delete")
                        .HasColumnType("int");

                    b.Property<int>("can_edit")
                        .HasColumnType("int");

                    b.Property<int>("can_view")
                        .HasColumnType("int");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("user_id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EnrollmentSystem.Models.Entities.Enroll", b =>
                {
                    b.HasOne("EnrollmentSystem.Models.Entities.Semester", "Semester")
                        .WithMany()
                        .HasForeignKey("Semestersem_id");

                    b.HasOne("EnrollmentSystem.Models.Entities.Student", "Student")
                        .WithMany()
                        .HasForeignKey("Studentstud_id");

                    b.HasOne("EnrollmentSystem.Models.Entities.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("Subjectsubj_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnrollmentSystem.Models.Entities.Course", "Course")
                        .WithMany()
                        .HasForeignKey("course_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnrollmentSystem.Models.Entities.Room", "Room")
                        .WithMany()
                        .HasForeignKey("room_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Room");

                    b.Navigation("Semester");

                    b.Navigation("Student");

                    b.Navigation("Subject");
                });
#pragma warning restore 612, 618
        }
    }
}
